#!/bin/bash


function help(){
    echo 'Usage:'
    echo '1) Run task manager:'
    echo 'neutuse run taskman [-a ADDR] [-b BACKEND] [-d]'
    echo 'ADDR: Default is 127.0.0.1:5000'
    echo 'BACKEND: Backend data base, default is sqlite:test.db'
    echo '-d debug mode'
    echo ''
    echo '2) Run service:'
    echo 'neutuse run service NAME [-a ADDR] [-n NUMBER]'
    echo 'ADDR: which address the task manager is running'
    echo 'Default ADDR is 127.0.0.1:5000'
    echo 'NAME: specifies service name'
    echo 'NUMBER: Numbers of tasks to fetch at each time'
    echo ''
    echo '3) Post task:'
    echo 'neutuse post FILE [-a ADDR]'
    echo 'ADDR: which address the task manager is running'
    echo 'Default ADDR is 127.0.0.1:5000'
    echo 'FILE: File describes the task'
    exit
}

function main(){
    case $1 in 

        'run'):
                case $2 in 
                'taskman'):
                    shift
                    shift
                    python run_taskman.py $*
                    exit
                    ;;
                'service'):
                    shift
                    shift
                    python run_service.py $*
                    exit
                    ;;
                *):
                    help
                    ;;
                esac
                ;;
        'post'):
                shift
                python post_task.py $*
                exit
                ;;
        *):
                help 
                ;; 

    esac
}

main $*

